# See https://pre-commit.com for more information

exclude: "dist/*"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-crlf
      - id: remove-tabs

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.15.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@5.16.0
          - eslint-config-airbnb@17.1.1
          - eslint-config-prettier@3.6.0
          - eslint-plugin-import@2.18.2
          - eslint-plugin-jsx-a11y@6.2.3
          - eslint-plugin-prettier@2.7.0
          - eslint-plugin-react@7.14.3
